#task:
#  - image-segmentation
#
#implementations:
#  torch:
#    tiled_metrics:
#      _target_: innofw.callbacks.lightning_callbacks.hub_segmentation_metrics.TiledHubSegmentationTestMetricsCalculation
#      threshold: 0.5
#      label_tensor_name: labels
#      filename_idx_tensor_name: file_idx
#      pad_map_tensor_name: pad_maps
#      stages:
#        fit:
#          file_info_hub_ds: /home/qazybek/GIS/qazybek/processed-data/arable/arable-s2-summer-92149a8e/hub/train_file_info
#          model_out_name: logits
#        val:
#          file_info_hub_ds: /home/qazybek/GIS/qazybek/processed-data/arable/arable-s2-summer-92149a8e/hub/val_file_info
#          model_out_name: logits
#        test:
#          file_info_hub_ds: /home/qazybek/GIS/qazybek/processed-data/arable/arable-s2-summer-92149a8e/hub/test_file_info
#          model_out_name: logits
#    gpu_stats:
#      object:
#        _target_: pytorch_lightning.callbacks.DeviceStatsMonitor

#    metrics_logger:
#      _target_: innofw.callbacks.lightning_callbacks.log_segmentation_metrics.LoggingSMPMetricsCallback
#      log_every_n_steps: 100
