name: Segmentation
description: Average of Jaccard and BinaryFocal losses
task:
  - image-segmentation

implementations:
  torch:
    JaccardLoss:
      weight: 0.5
      object:
        _target_: pytorch_toolbelt.losses.JaccardLoss
        mode: binary
    BinaryFocalLoss:
      weight: 0.5
      object:
        _target_: pytorch_toolbelt.losses.BinaryFocalLoss
