_target_: innofw.core.datamodules.lightning_datamodules.segmentation_dir.DirSegmentationLightningDataModule
date_time: 30.09.2022
description: stroke segmentation dataset
markup_info: segmentation masks
name: stroke segmentation
task: image-segmentation
test:
  source: ./innofw/shm/test
train:
  source: ./innofw/shm/train
infer:
  source: ./innofw/shm/infer
