task:
  - image-segmentation

name: test dataset
description: dataset for running training in hdf5 format
markup_info: Информация о разметке
date_time: 03.09.2030

_target_: innofw.core.datamodules.lightning_datamodules.segmentation_hdf5_dm.HDF5LightningDataModule

train:
  source: /mnt/datastore/GIS/qazybek/segmentation_pipelines/arable-EIR/hdf5-06-06/512/train_samples.hdf5

test:
  source: /mnt/datastore/GIS/qazybek/segmentation_pipelines/arable-EIR/hdf5-06-06/512/val_samples.hdf5

#infer:
#  source: /mnt/localssd/qazybek/innofw/data/images/segmentation/arable/cropped

val_size: 0.2
channels_num: 4
num_workers: 8
