task:
  - image-segmentation

name: test dataset
description: dataset for running training in hdf5 format
markup_info: Информация о разметке
date_time: 03.09.2030


train:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/arable/train.zip
  target: ./data/arable/train/

test:
  source: https://api.blackhole.ai.innopolis.university/public-datasets/arable/test.zip
  target: ./data/arable/test/
val_size: 0.2
channels_num: 4
