defaults:
  - _self_
  - datasets: 
  - models: 
  - trainer: auto
  - metrics: auto
  - losses: auto
  - optimizers: auto
  - schedulers: auto
  - augmentations: none
  - loggings: auto
  - callbacks: auto
  - initializations:
  - wandb: default
  - experiments:  # order matters
  - clear_ml: disabled
  - override hydra/job_logging: disabled
#  - override hydra/job_logging: custom

project: 
task: 
random_seed:
epochs:
batch_size:
weights_path:
weights_freq:
ckpt_path:
stop_param:

accelerator: gpu
devices: 1
gpus: 1
