name: SGD
description: Popular optimizer works better then Adam for some tasks
task:
  - all

implementations:
  torch:
    SGD:
      function:
        _target_: innofw.core.optimizers.custom_optimizers.optimizers.SGD
        lr: 1e-5
