task:
  - image-segmentation

implementations:
  torch:
    Compose:
      object:
        _target_: albumentations.Compose
        transforms:
          - _target_: albumentations.transforms.PadIfNeeded
            pad_height_divisor: 8
            pad_width_divisor: 8
            min_height:
            min_width:
