name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag innofw:$(date +%s)

  build-on-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Preparing Env
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        set PATH=%PATH%;C:\Users\runneradmin\AppData\Roaming\Python\Scripts
        poetry config virtualenvs.create true
        poetry install
        poetry run pytest tests/

  build-on-astra:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file DockerfileAstra --tag innofw
        docker run -t innofw
